services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TuPasswordFuerte123!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P TuPasswordFuerte123! -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      retries: 20
      start_period: 30s

  ingesta:
    build: ./app
    container_name: python_ingestion
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app
      - ./datos:/datos
    environment:
      - DB_HOST=db
      - DB_USER=sa
      - DB_PASS=TuPasswordFuerte123!
    command: tail -f /dev/null  # Mantener el contenedor en ejecuci√≥n para pruebas

volumes:
  sql_data:

 
